import "./globals.css";
import type { Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs";
import { ToastProvider } from "@/components/providers/toaster-provider";
import { ThemeProvider } from "next-themes";
import { ModeToggle } from "@/components/ui/mode-toggle";
import ClerkThemeProvider from "@/components/clerk-theme-provider";

export const metadata: Metadata = {
  metadataBase: new URL("https://localhost:3000"),
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="!font-Poppins" suppressHydrationWarning>
      <body className="dark:bg-background-1st-level dark:border-background-1st-level">
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <ClerkThemeProvider>
            <ModeToggle />
            <ToastProvider />
            {children}
          </ClerkThemeProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
